// Pure data: the palette's category tabs and per-building icons.
import {
  Beer,
  Bell,
  BrickWall,
  Building2,
  Castle,
  Church,
  Columns3,
  Cross,
  DraftingCompass,
  Droplets,
  Fence,
  Flame,
  Footprints,
  Gem,
  Grape,
  Hammer,
  Home,
  Landmark,
  Milestone,
  Mountain,
  Palette,
  PersonStanding,
  Pickaxe,
  Pyramid,
  Route,
  Shovel,
  Shrub,
  Store,
  Tent,
  TreeDeciduous,
  TreePine,
  Trees,
  Warehouse,
  Waves,
  Wheat,
  type LucideIcon,
} from "lucide-react";

import type { BuildingId } from "~/game/buildings";
import type { BuildingType } from "~/game/types";

export const CATEGORIES: Array<{ type: BuildingType; label: string; icon: LucideIcon }> = [
  { type: "road", label: "Roads", icon: Route },
  { type: "city", label: "Civic", icon: Landmark },
  { type: "residential", label: "Housing", icon: Home },
  { type: "service", label: "Services", icon: Wheat },
  { type: "artist", label: "Workshops", icon: Palette },
  { type: "materials", label: "Materials", icon: Hammer },
  { type: "decoration", label: "Decorations", icon: TreePine },
];

export const BUILDING_ICONS: Record<BuildingId, LucideIcon> = {
  town_center_plaza: Landmark,
  plaza: Landmark,
  small_plaza: Landmark,
  palazzo: Castle,
  cathedral: Church,
  chapel: Cross,
  loggia: Columns3,
  baptistery: Church,
  bell_tower: Bell,
  workshop: Palette,
  sculpture_workshop: Hammer,
  architect_studio: DraftingCompass,
  cottage: Home,
  townhouse: Building2,
  pigment_trader: Palette,
  marble_supplier: Gem,
  bronze_foundry: Flame,
  timber_yard: Trees,
  stone_quarry: Pickaxe,
  warehouse: Warehouse,
  market: Store,
  bakery: Wheat,
  tavern: Beer,
  market_stall: Tent,
  dirt_path: Shovel,
  path: Footprints,
  road: Route,
  avenue: Milestone,
  bridge: Waves,
  tree: TreeDeciduous,
  cypress: TreePine,
  vineyard: Grape,
  fountain: Droplets,
  colonnade: Columns3,
  obelisk: Pyramid,
  olive_grove: Trees,
  bush: Shrub,
  rocks: Mountain,
  boulder: Mountain,
  fence: Fence,
  stone_wall: BrickWall,
  sculpture_display: PersonStanding,
};
