// Pixelated public-domain paintings keyed by artwork title (generated by
// scripts/make-pixel-art.py from Wikimedia Commons PD-Art). Titles without an
// entry keep the procedural canvas / placeholder thumbnail. Lives next to the
// title pools (artists.ts) so title edits and image coverage stay in one dir.
export const ART_IMAGES: Record<string, string> = {
  "Allegory of Spring": "/art/allegory-of-spring.png",
  "The Annunciation": "/art/the-annunciation.png",
  "The Adoration of the Magi": "/art/the-adoration-of-the-magi.png",
  "Portrait of a Young Merchant": "/art/portrait-of-a-young-merchant.png",
};

// Low-poly statue scans (scripts/make-low-poly-statue.py, threedscans.com)
// keyed by artwork title; GLBs are normalized to feet-at-origin, height 1.
// Every sculpture title in the pools (artists.ts) is a real work with a real
// scan — the map covers all twelve, so the procedural statue variants only
// serve pre-Aug-2026 saves holding retired titles. 600 tris apiece (the Aug
// 2026 baseline); the reclining Pan gets 1200, which its
// figure-plus-base composition needs.
export const STATUE_MODELS: Record<string, string> = {
  // Secular — antiquities, collected all'antica
  Cincinnatus: "/models/statues/cincinnatus.glb",
  "The Spinario": "/models/statues/thorn.glb",
  Neptune: "/models/statues/neptune.glb",
  "The Reclining Pan": "/models/statues/pan.glb",
  // Church
  "The Transi of René de Chalon": "/models/statues/transi.glb",
  "Saint Hugh": "/models/statues/hugh.glb",
  "Queen Margaret": "/models/statues/margaret.glb",
  // Bronze casts — originals cast in bronze
  "Theodoric the Great": "/models/statues/theodoric.glb",
  "The Minerva of Arezzo": "/models/statues/minerva.glb",
  "The Orator": "/models/statues/orator.glb",
  "Hermes Fastening His Sandal": "/models/statues/hermes.glb",
};
