// Pixelated public-domain paintings keyed by artwork title (generated by
// scripts/make-pixel-art.py from Wikimedia Commons PD-Art). Titles without an
// entry keep the procedural canvas / placeholder thumbnail. Lives next to the
// title pools (artists.ts) so title edits and image coverage stay in one dir.
export const ART_IMAGES: Record<string, string> = {
  "Allegory of Spring": "/art/allegory-of-spring.png",
  "The Annunciation": "/art/the-annunciation.png",
  "The Adoration of the Magi": "/art/the-adoration-of-the-magi.png",
  "Portrait of a Young Merchant": "/art/portrait-of-a-young-merchant.png",
};

// Low-poly statue scans (scripts/make-low-poly-statue.py, threedscans.com)
// keyed by artwork title; GLBs are normalized to feet-at-origin, height 1.
// Unmapped titles keep the procedural statue variants.
// All scans decimated to 600 tris (the baseline picked from the Aug 2026
// tri-target test; 1200 read a fidelity tier above the kit, 300 got chunky on
// complex poses). Title→scan pairing is provisional until the roster from
// docs/artifacts/statue-scan-catalog.md is chosen.
export const STATUE_MODELS: Record<string, string> = {
  "David in Marble": "/models/statues/cincinnatus.glb",
  "Nymph of the Arno": "/models/statues/eve.glb",
  Bacchus: "/models/statues/hermes.glb",
  "The Three Graces": "/models/statues/thorn.glb",
};
