// Pixelated public-domain paintings keyed by artwork title (generated by
// scripts/make-pixel-art.py from Wikimedia Commons PD-Art). Every painting
// title in the pools (artists.ts) is a real work with its own source, so the
// map covers all twenty-four and the procedural canvas only serves
// pre-Aug-2026 saves holding retired titles. Lives next to the title pools so
// title edits and image coverage stay in one dir. Source shortlist (aspect
// ratios, benched works, why): docs/artifacts/painting-source-catalog.md.
export const ART_IMAGES: Record<string, string> = {
  // Secular — portraits, allegories, the city's own trades
  "Allegory of Spring": "/art/allegory-of-spring.png",
  "The Birth of Venus": "/art/the-birth-of-venus.png",
  "Lady with an Ermine": "/art/lady-with-an-ermine.png",
  "Mona Lisa": "/art/mona-lisa.png",
  "Portrait of a Man with a Medal": "/art/portrait-of-a-man-with-a-medal.png",
  "An Old Man and His Grandson": "/art/an-old-man-and-his-grandson.png",
  "Portrait of Baldassare Castiglione": "/art/portrait-of-baldassare-castiglione.png",
  "The School of Athens": "/art/the-school-of-athens.png",
  "The Tempest": "/art/the-tempest.png",
  "Pallas and the Centaur": "/art/pallas-and-the-centaur.png",
  "A Goldsmith in His Shop": "/art/a-goldsmith-in-his-shop.png",
  "The Moneylender and His Wife": "/art/the-moneylender-and-his-wife.png",
  // Church
  "The Annunciation": "/art/the-annunciation.png",
  "The Adoration of the Magi": "/art/the-adoration-of-the-magi.png",
  "Saint Jerome in His Study": "/art/saint-jerome-in-his-study.png",
  "The Last Judgment": "/art/the-last-judgment.png",
  "The Madonna of the Goldfinch": "/art/the-madonna-of-the-goldfinch.png",
  "The Sistine Madonna": "/art/the-sistine-madonna.png",
  "The Lamentation of Christ": "/art/the-lamentation-of-christ.png",
  "The Baptism of Christ": "/art/the-baptism-of-christ.png",
  "The Mystical Nativity": "/art/the-mystical-nativity.png",
  "The Annunciation with Saint Emidius": "/art/the-annunciation-with-saint-emidius.png",
  "The Expulsion from the Garden of Eden": "/art/the-expulsion-from-the-garden-of-eden.png",
  "The Montefeltro Altarpiece": "/art/the-montefeltro-altarpiece.png",
};

// Low-poly statue scans (scripts/make-low-poly-statue.py, threedscans.com)
// keyed by artwork title; GLBs are normalized to feet-at-origin, height 1.
// Every sculpture title in the pools (artists.ts) is a real work with a real
// scan — the map covers all twelve, so the procedural statue variants only
// serve pre-Aug-2026 saves holding retired titles. 600 tris apiece (the Aug
// 2026 baseline); the reclining Pan gets 1200, which its
// figure-plus-base composition needs.
export const STATUE_MODELS: Record<string, string> = {
  // Secular — antiquities, collected all'antica
  Cincinnatus: "/models/statues/cincinnatus.glb",
  "The Spinario": "/models/statues/thorn.glb",
  Neptune: "/models/statues/neptune.glb",
  "The Reclining Pan": "/models/statues/pan.glb",
  // Church
  "The Transi of René de Chalon": "/models/statues/transi.glb",
  "Saint Hugh": "/models/statues/hugh.glb",
  "Queen Margaret": "/models/statues/margaret.glb",
  // Bronze casts — originals cast in bronze
  "Theodoric the Great": "/models/statues/theodoric.glb",
  "The Minerva of Arezzo": "/models/statues/minerva.glb",
  "The Orator": "/models/statues/orator.glb",
  "Hermes Fastening His Sandal": "/models/statues/hermes.glb",
};
